import xlsxwriter as xs
workbook = xs.Workbook("smallcases.xlsx")
workseed = workbook.add_worksheet('first')
workseed.write(0, 1, 'Title')
workseed.write(0, 2, 'Managed By')
workseed.write(0, 3, 'Small description')
workseed.write(0, 4, 'CAGR Time period')
workseed.write(0, 5, 'CAGR Rate')
workseed.write(0, 6, 'Volatility')
workseed.write(0, 7, 'Overview')
workseed.write(0, 8, 'Minimum Investment Amount')
workseed.write(0, 9, 'Launch date')
workseed.write(0, 10, 'Past Perfomance:Small case')
workseed.write(0, 11, 'Past Perfomance:Equity')
workseed.write(0, 12, 'Past Perfomance:FD')
workseed.write(0, 13, 'Past Perfomance:Inflation')
workseed.write(0, 14, 'CAGR:Small case')
workseed.write(0, 15, 'CAGR:Equity')
workseed.write(0, 16, 'CAGR:FD')
workseed.write(0, 17, 'CAGRe:Inflation')
workseed.write(0, 18, 'Number of small cases by manager')
workseed.write(0, 19, 'About Manager')